inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:

  TargetRubyVersion: 2.5


  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/


Style/AsciiComments:
  Enabled: true


Style/Documentation:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true
